FROM debian:bookworm

#	Update packet installer
RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y wget php8.2 php-fpm php-mysql mariadb-client && \
	wget https://fr.wordpress.org/wordpress-6.0-fr_FR.tar.gz -P /var/www && \
	cd /var/www && tar -xzf wordpress-6.0-fr_FR.tar.gz && \
	rm /var/www/wordpress-6.0-fr_FR.tar.gz && \
	chown -R www-data:www-data /var/www/wordpress && \
	wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
#	1 - Install all the dependencies required for WordPress
#	2 - Download the WordPress ZIP file
#	3 - Change directories and unzip
#	4 - Delete the extracted .tar file
#	5 - Change the owner directory after extraction
#	6 - Download CLI configuration service wordpress


#	Replace the configuration file
COPY conf/www.conf /etc/php/8.2/fpm/pool.d/www.conf
#	Copy the script to install WordPress
COPY tools/auto-config.sh /usr/local/bin/auto-config.sh

RUN chmod +x /usr/local/bin/auto-config.sh

#	Change the working directory
WORKDIR /var/www/wordpress

ENTRYPOINT [ "/usr/local/bin/auto-config.sh" ]

CMD [ "/usr/sbin/php-fpm8.2", "-F" ]